databases:
  - name: parul-db
    databaseName: parul_db
    user: parul_user
    plan: free

services:
  - type: web
    name: new-parul-diagnostic
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt && pip install gunicorn"
    startCommand: "cd backend && gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: parul-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.10.0"
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
